# src/OC/PlatformBundle/Resources/config/routing.yml

oc_platform_home:
    path:      /
    defaults:  { _controller: OCPlatformBundle:Advert:index }
    
oc_platform_contact:
    path:     /contact
    defaults:  { _controller: OCPlatformBundle:Advert:contact }
    
oc_platform_pricing:
    path:      /pricing
    defaults:  { _controller: OCPlatformBundle:Advert:pricing }

oc_platform_about:
    path:      /about
    defaults:  { _controller: OCPlatformBundle:Advert:about }
    
oc_platform_log_reg:
    path:      /log_reg
    defaults:  { _controller: OCPlatformBundle:Advert:log_reg }
    
oc_platform_unity:
    path:      /unity
    defaults:  { _controller: OCPlatformBundle:Advert:unity }